-- Populate the states table with US states, territories, and military codes
INSERT INTO states (code, name) VALUES
  ('OK', 'Oklahoma'),
  ('TN', 'Tennessee'),
  ('FL', 'Florida'),
  ('TX', 'Texas'),
  ('CA', 'California'),
  ('NE', 'Nebraska'),
  ('IL', 'Illinois'),
  ('CO', 'Colorado'),
  ('UT', 'Utah'),
  ('WI', 'Wisconsin'),
  ('NM', 'New Mexico'),
  ('MN', 'Minnesota'),
  ('IN', 'Indiana'),
  ('OH', 'Ohio'),
  ('WA', 'Washington'),
  ('GA', 'Georgia'),
  ('KY', 'Kentucky'),
  ('NC', 'North Carolina'),
  ('PA', 'Pennsylvania'),
  ('WY', 'Wyoming'),
  ('IA', 'Iowa'),
  ('MA', 'Massachusetts'),
  ('MI', 'Michigan'),
  ('MT', 'Montana'),
  ('NJ', 'New Jersey'),
  ('ME', 'Maine'),
  ('ID', 'Idaho'),
  ('AK', 'Alaska'),
  ('AR', 'Arkansas'),
  ('NH', 'New Hampshire'),
  ('OR', 'Oregon'),
  ('NY', 'New York'),
  ('MO', 'Missouri'),
  ('VA', 'Virginia'),
  ('MS', 'Mississippi'),
  ('LA', 'Louisiana'),
  ('DE', 'Delaware'),
  ('MD', 'Maryland'),
  ('SC', 'South Carolina'),
  ('CT', 'Connecticut'),
  ('SD', 'South Dakota'),
  ('WV', 'West Virginia'),
  ('AZ', 'Arizona'),
  ('DC', 'District of Columbia'),
  ('KS', 'Kansas'),
  ('HI', 'Hawaii'),
  ('ND', 'North Dakota'),
  ('AL', 'Alabama'),
  ('NV', 'Nevada'),
  ('VT', 'Vermont'),
  ('RI', 'Rhode Island'),
  ('PR', 'Puerto Rico'),
  ('MP', 'Northern Mariana Islands'),
  ('AP', 'Armed Forces Pacific'),
  ('GU', 'Guam'),
  ('VI', 'U.S. Virgin Islands'),
  ('AE', 'Armed Forces Europe'),
  ('AS', 'American Samoa');
