-- Populate the countries table with common country codes used in FAA data
INSERT INTO countries (code, name) VALUES
  ('US', 'United States'),
  ('CA', 'Canada'),
  ('MX', 'Mexico'),
  ('GB', 'United Kingdom'),
  ('DE', 'Germany'),
  ('FR', 'France'),
  ('IT', 'Italy'),
  ('ES', 'Spain'),
  ('NL', 'Netherlands'),
  ('CH', 'Switzerland'),
  ('AT', 'Austria'),
  ('BE', 'Belgium'),
  ('SE', 'Sweden'),
  ('NO', 'Norway'),
  ('DK', 'Denmark'),
  ('FI', 'Finland'),
  ('IE', 'Ireland'),
  ('PT', 'Portugal'),
  ('GR', 'Greece'),
  ('PL', 'Poland'),
  ('CZ', 'Czech Republic'),
  ('HU', 'Hungary'),
  ('SK', 'Slovakia'),
  ('SI', 'Slovenia'),
  ('HR', 'Croatia'),
  ('RO', 'Romania'),
  ('BG', 'Bulgaria'),
  ('EE', 'Estonia'),
  ('LV', 'Latvia'),
  ('LT', 'Lithuania'),
  ('LU', 'Luxembourg'),
  ('MT', 'Malta'),
  ('CY', 'Cyprus'),
  ('IS', 'Iceland'),
  ('LI', 'Liechtenstein'),
  ('MC', 'Monaco'),
  ('SM', 'San Marino'),
  ('VA', 'Vatican City'),
  ('AD', 'Andorra'),
  ('JP', 'Japan'),
  ('AU', 'Australia'),
  ('NZ', 'New Zealand'),
  ('KR', 'South Korea'),
  ('CN', 'China'),
  ('IN', 'India'),
  ('BR', 'Brazil'),
  ('AR', 'Argentina'),
  ('CL', 'Chile'),
  ('CO', 'Colombia'),
  ('PE', 'Peru'),
  ('VE', 'Venezuela'),
  ('UY', 'Uruguay'),
  ('PY', 'Paraguay'),
  ('BO', 'Bolivia'),
  ('EC', 'Ecuador'),
  ('GY', 'Guyana'),
  ('SR', 'Suriname'),
  ('GF', 'French Guiana'),
  ('ZA', 'South Africa'),
  ('EG', 'Egypt'),
  ('MA', 'Morocco'),
  ('TN', 'Tunisia'),
  ('DZ', 'Algeria'),
  ('LY', 'Libya'),
  ('SD', 'Sudan'),
  ('ET', 'Ethiopia'),
  ('KE', 'Kenya'),
  ('TZ', 'Tanzania'),
  ('UG', 'Uganda'),
  ('RW', 'Rwanda'),
  ('BI', 'Burundi'),
  ('DJ', 'Djibouti'),
  ('SO', 'Somalia'),
  ('ER', 'Eritrea'),
  ('SS', 'South Sudan'),
  ('CF', 'Central African Republic'),
  ('TD', 'Chad'),
  ('CM', 'Cameroon'),
  ('NG', 'Nigeria'),
  ('NE', 'Niger'),
  ('BF', 'Burkina Faso'),
  ('ML', 'Mali'),
  ('SN', 'Senegal'),
  ('GM', 'Gambia'),
  ('GW', 'Guinea-Bissau'),
  ('GN', 'Guinea'),
  ('SL', 'Sierra Leone'),
  ('LR', 'Liberia'),
  ('CI', 'Côte d''Ivoire'),
  ('GH', 'Ghana'),
  ('TG', 'Togo'),
  ('BJ', 'Benin'),
  ('GA', 'Gabon'),
  ('GQ', 'Equatorial Guinea'),
  ('ST', 'São Tomé and Príncipe'),
  ('AO', 'Angola'),
  ('ZM', 'Zambia'),
  ('ZW', 'Zimbabwe'),
  ('BW', 'Botswana'),
  ('NA', 'Namibia'),
  ('SZ', 'Eswatini'),
  ('LS', 'Lesotho'),
  ('MZ', 'Mozambique'),
  ('MW', 'Malawi'),
  ('MG', 'Madagascar'),
  ('MU', 'Mauritius'),
  ('SC', 'Seychelles'),
  ('KM', 'Comoros'),
  ('YT', 'Mayotte'),
  ('RE', 'Réunion'),
  ('RU', 'Russia'),
  ('UA', 'Ukraine'),
  ('BY', 'Belarus'),
  ('MD', 'Moldova'),
  ('GE', 'Georgia'),
  ('AM', 'Armenia'),
  ('AZ', 'Azerbaijan'),
  ('KZ', 'Kazakhstan'),
  ('KG', 'Kyrgyzstan'),
  ('TJ', 'Tajikistan'),
  ('TM', 'Turkmenistan'),
  ('UZ', 'Uzbekistan'),
  ('MN', 'Mongolia'),
  ('TR', 'Turkey'),
  ('SY', 'Syria'),
  ('LB', 'Lebanon'),
  ('JO', 'Jordan'),
  ('IL', 'Israel'),
  ('PS', 'Palestine'),
  ('SA', 'Saudi Arabia'),
  ('YE', 'Yemen'),
  ('OM', 'Oman'),
  ('AE', 'United Arab Emirates'),
  ('QA', 'Qatar'),
  ('BH', 'Bahrain'),
  ('KW', 'Kuwait'),
  ('IQ', 'Iraq'),
  ('IR', 'Iran'),
  ('AF', 'Afghanistan'),
  ('PK', 'Pakistan'),
  ('BD', 'Bangladesh'),
  ('LK', 'Sri Lanka'),
  ('MV', 'Maldives'),
  ('NP', 'Nepal'),
  ('BT', 'Bhutan'),
  ('MM', 'Myanmar'),
  ('TH', 'Thailand'),
  ('LA', 'Laos'),
  ('KH', 'Cambodia'),
  ('VN', 'Vietnam'),
  ('MY', 'Malaysia'),
  ('SG', 'Singapore'),
  ('BN', 'Brunei'),
  ('ID', 'Indonesia'),
  ('TL', 'Timor-Leste'),
  ('PH', 'Philippines'),
  ('TW', 'Taiwan'),
  ('HK', 'Hong Kong'),
  ('MO', 'Macao'),
  ('FJ', 'Fiji'),
  ('PG', 'Papua New Guinea'),
  ('SB', 'Solomon Islands'),
  ('VU', 'Vanuatu'),
  ('NC', 'New Caledonia'),
  ('PF', 'French Polynesia'),
  ('WS', 'Samoa'),
  ('TO', 'Tonga'),
  ('KI', 'Kiribati'),
  ('TV', 'Tuvalu'),
  ('NR', 'Nauru'),
  ('PW', 'Palau'),
  ('FM', 'Micronesia'),
  ('MH', 'Marshall Islands'),
  ('CK', 'Cook Islands'),
  ('NU', 'Niue'),
  ('TK', 'Tokelau'),
  ('WF', 'Wallis and Futuna'),
  ('AS', 'American Samoa'),
  ('GU', 'Guam'),
  ('MP', 'Northern Mariana Islands'),
  ('VI', 'U.S. Virgin Islands'),
  ('RQ', 'Puerto Rico'),
  ('UM', 'U.S. Minor Outlying Islands');
