-- Rollback: Clear analytics tables
-- This is destructive but safe since the data can be re-generated by re-running the up migration

TRUNCATE TABLE flight_analytics_daily;
TRUNCATE TABLE flight_analytics_hourly;
TRUNCATE TABLE aircraft_analytics;
TRUNCATE TABLE club_analytics_daily;
TRUNCATE TABLE airport_analytics_daily;

-- Reset flight_duration_buckets counts to zero
UPDATE flight_duration_buckets SET flight_count = 0, updated_at = NOW();
