#!/usr/bin/env node

/**
 * Generate version.ts from git describe
 *
 * This script runs `git describe --tags --always --dirty` to get the current version
 * from git metadata and generates a TypeScript module that exports the version.
 *
 * The version format is:
 * - For tagged commits: the tag name (e.g., "v0.1.4")
 * - For commits after a tag: tag + commits + hash (e.g., "v0.1.4-2-ge930185")
 * - For dirty working trees: appends "-dirty" (e.g., "v0.1.4-dirty")
 * - For non-git environments: falls back to "0.0.0-dev"
 */

import { execSync } from 'child_process';
import { writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/**
 * Get version from git describe
 * @returns {string} Version string from git or fallback
 */
function getGitVersion() {
	try {
		const version = execSync('git describe --tags --always --dirty', {
			encoding: 'utf-8',
			stdio: ['pipe', 'pipe', 'ignore']
		}).trim();

		if (!version) {
			console.warn('⚠️  Git describe returned empty string, using fallback version');
			return '0.0.0-dev';
		}

		return version;
	} catch (error) {
		console.warn('⚠️  Git not available or not a git repository, using fallback version');
		console.warn('   Error:', error.message);
		return '0.0.0-dev';
	}
}

const version = getGitVersion();
const buildTime = new Date().toISOString();

const content = `// This file is auto-generated by scripts/generate-version.js
// Do not edit manually - changes will be overwritten on next build

/**
 * Application version derived from git tags
 *
 * Format:
 * - Tagged release: "v0.1.4"
 * - Development build: "v0.1.4-2-ge930185" (2 commits after v0.1.4, commit e930185)
 * - Dirty working tree: "v0.1.4-dirty"
 * - No git repo: "0.0.0-dev"
 */
export const VERSION = '${version}';

/**
 * Build timestamp in ISO 8601 format
 */
export const BUILD_TIME = '${buildTime}';

/**
 * Short version without 'v' prefix (for display purposes)
 */
export const VERSION_SHORT = VERSION.replace(/^v/, '');
`;

const outputPath = join(__dirname, '../src/lib/version.ts');

try {
	writeFileSync(outputPath, content, 'utf-8');
	console.log(`✅ Generated version info: ${version}`);
	console.log(`   Build time: ${buildTime}`);
	console.log(`   Output: ${outputPath}`);
} catch (error) {
	console.error('❌ Failed to write version.ts:', error.message);
	process.exit(1);
}
