# Grafana Alerting Rules Configuration - STAGING ONLY
# This defines the alert conditions and thresholds for SOAR staging monitoring
#
# This file should ONLY be deployed to staging Grafana instances.
# For production alerts, see alert-rules-production.yml

apiVersion: 1

groups:
  # ============================================================================
  # STAGING ENVIRONMENT ALERTS
  # ============================================================================
  - orgId: 1
    name: soar-ogn-ingest-alerts-staging
    folder: SOAR
    interval: 1m
    rules:
      # Alert when staging OGN/APRS message ingestion rate drops below 1 message per minute
      - uid: ogn_message_rate_low_staging
        title: "[Staging] OGN Message Ingestion Rate Too Low"
        condition: C
        data:
          # Query A: Get the rate of APRS messages processed per minute (staging only)
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: Prometheus
            model:
              expr: rate(aprs_raw_message_processed_total{environment="staging"}[1m]) * 60
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A

          # Query B: Get the rate of messages published to NATS per minute (staging only)
          - refId: B
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: Prometheus
            model:
              expr: rate(aprs_nats_published_total{environment="staging"}[1m]) * 60
              intervalMs: 1000
              maxDataPoints: 43200
              refId: B

          # Condition C: Alert if metric is below 1 msg/min
          - refId: C
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 1
                    type: lt
                  operator:
                    type: and
                  query:
                    params:
                      - A
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold

        for: 2m
        noDataState: OK
        execErrState: Alerting
        annotations:
          summary: "[Staging] OGN/APRS message ingestion rate is critically low"
          description: 'Staging OGN ingestion rate: {{ printf "%.2f" $values.A.Value }} messages/min (threshold: 1.0 msg/min). Check if ingest-ogn-staging service is running and connected to APRS-IS.'
        labels:
          severity: critical
          service: ogn-ingest
          environment: staging
          team: ops

      # Alert when staging OGN ingest service is disconnected
      - uid: ogn_service_disconnected_staging
        title: "[Staging] OGN Ingest Service Disconnected"
        condition: B
        data:
          # Query A: Check if APRS connection is established (staging only)
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: Prometheus
            model:
              expr: aprs_connection_connected{environment="staging"}
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A

          # Condition B: Alert if connection gauge is 0 (disconnected)
          - refId: B
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 0.5
                    type: lt
                  operator:
                    type: and
                  query:
                    params:
                      - A
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              refId: B
              type: threshold

        for: 1m
        noDataState: OK
        execErrState: Alerting
        annotations:
          summary: "[Staging] OGN/APRS ingest service is disconnected"
          description: 'The staging OGN ingest service has lost connection to APRS-IS. Check service status and network connectivity.'
        labels:
          severity: critical
          service: ogn-ingest
          environment: staging
          team: ops

      # Alert when staging NATS publishing errors are occurring
      - uid: ogn_nats_publish_errors_staging
        title: "[Staging] OGN NATS Publishing Errors"
        condition: B
        data:
          # Query A: Get the rate of NATS publish errors (staging only)
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: Prometheus
            model:
              expr: rate(aprs_nats_publish_error_total{environment="staging"}[5m]) * 60
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A

          # Condition B: Alert if error rate > 0.1 errors/min
          - refId: B
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 0.1
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - A
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              refId: B
              type: threshold

        for: 3m
        noDataState: OK
        execErrState: Alerting
        annotations:
          summary: "[Staging] OGN ingest service is experiencing NATS publishing errors"
          description: 'Staging NATS publish error rate: {{ printf "%.2f" $values.A.Value }} errors/min. Check NATS connectivity and queue depth.'
        labels:
          severity: warning
          service: ogn-ingest
          environment: staging
          team: ops
