server:
  http_listen_address: 127.0.0.1
  http_listen_port: 3200
  grpc_listen_address: 127.0.0.1
  grpc_listen_port: 9097

distributor:
  receivers:
    otlp:
      protocols:
        http:
          endpoint: 127.0.0.1:4320

memberlist:
  bind_addr:
    - "127.0.0.1"
  bind_port: 7946

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  trace_idle_period: 10s
  max_block_bytes: 104857600
  max_block_duration: 5m

# Metrics generator for TraceQL metrics queries
metrics_generator:
  ring:
    kvstore:
      store: inmemory
  processor:
    service_graphs:
      dimensions:
        - service.namespace
    span_metrics:
      dimensions:
        - service.namespace
    local_blocks:
      filter_server_spans: false
  storage:
    path: /var/lib/tempo/generator/wal
    remote_write:
      - url: http://127.0.0.1:9090/api/v1/write
        send_exemplars: true
  traces_storage:
    path: /var/lib/tempo/generator/traces

compactor:
  compaction:
    block_retention: 168h  # 7 days

storage:
  trace:
    backend: local
    local:
      path: /var/lib/tempo/blocks
    wal:
      path: /var/lib/tempo/wal

overrides:
  defaults:
    ingestion:
      rate_limit_bytes: 15000000
      burst_size_bytes: 20000000
    metrics_generator:
      processors:
        - service-graphs
        - span-metrics
        - local-blocks
