server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

ingester:
  max_block_duration: 5m               # cut the headblock when this much time passes

compactor:
  compaction:
    block_retention: 168h              # 7 days retention

storage:
  trace:
    backend: local                      # use local filesystem for traces
    wal:
      path: /tmp/tempo/wal              # write ahead log location
    local:
      path: /tmp/tempo/blocks            # blocks storage location

query_frontend:
  search:
    max_duration: 0s                     # allow searching all time ranges
