-- This migration was originally intended to VALIDATE CONSTRAINT on the two
-- FK constraints on fixes (fixes_aircraft_id_fkey, fixes_flight_id_fkey)
-- that were created with NOT VALID.
--
-- However, VALIDATE CONSTRAINT is not supported on TimescaleDB hypertables
-- with columnstore (compression) enabled, so we skip it.
--
-- The NOT VALID constraints still enforce referential integrity on all new
-- inserts and updates. Validation would only confirm that pre-existing rows
-- are valid, which is already guaranteed since the retention policy has
-- cleaned up any orphaned rows.
SELECT 1;
